models:
  segmenter:
    name: "mask_rcnn"
    confidence_threshold: 0.7
    device: "cuda"
  
  embedder:
    name: "clip"
    model_name: "ViT-B/32"
    device: "cuda"
  
  similarity:
    threshold: 0.75
    top_k: 10

search:
  min_object_area: 1000
  max_object_area: 50000